# Generated by Django 5.1.6 on 2025-03-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reserve",
            fields=[
                ("reserveNum", models.AutoField(primary_key=True, serialize=False)),
                ("petNum", models.IntegerField()),
                ("managerNum", models.IntegerField()),
                (
                    "reserveStatus",
                    models.CharField(
                        choices=[("대기", "대기"), ("완료", "완료"), ("취소", "취소")],
                        default="대기",
                        max_length=10,
                    ),
                ),
                ("reserveDate", models.DateTimeField()),
                ("reserveNotice", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("userNum", models.AutoField(primary_key=True, serialize=False)),
                ("userName", models.CharField(max_length=50)),
                ("userId", models.CharField(max_length=50, unique=True)),
                ("userPwd", models.CharField(max_length=100)),
                ("userPhone", models.CharField(max_length=15, unique=True)),
                ("userBirth", models.DateField()),
                ("userEmail", models.EmailField(max_length=254, unique=True)),
                ("userAddress", models.CharField(max_length=100)),
                ("userAddressNum", models.CharField(max_length=5)),
                (
                    "userStatus",
                    models.CharField(
                        choices=[("활성", "활성"), ("비활성", "비활성")],
                        default="활성",
                        max_length=10,
                    ),
                ),
                ("userSignupDate", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
