# Generated by Django 5.1.6 on 2025-03-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CoolSMS", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserve",
            name="reserveNotice",
            field=models.CharField(max_length=500),
        ),
    ]
