# Generated by Django 5.1.6 on 2025-03-06 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CoolSMS", "0002_alter_reserve_reservenotice"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reserve",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
