# curl -X GET "localhost:9200/animal_symptoms/_search?pretty" -H "Content-Type: application/json" -d'
#{
#  "query": {
#    "match_all": {}
#  },
#  "size": 1
#}'
GET localhost:9200/animal_symptoms/_search?pretty
Content-Type: application/json


{
  "query": {
    "match_all": {}
  },
  "size": 1
}

###

