# Generated by Django 5.1.6 on 2025-03-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mse", models.FloatField()),
                ("normalAboveThreshold", models.FloatField()),
                ("anomalyProbability", models.FloatField()),
                ("isAnomaly", models.BooleanField()),
                ("userIP", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
