# Generated by Django 5.1.6 on 2025-03-06 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="paymentcard",
            table="PAYMENTCARD",
        ),
    ]
